### ISSUE TITLE
¿Qué es una solicitud de fusión?

### ISSUE THREAD

**Issue by KiyoshiRM** [cthed2/ChatGPT_API#22]

**Comment by Jalorca** [comment]
Antes de definir lo que es una "solicitud de fusión" o un "pull request", es necesario tener en cuenta la definición de "issues" o "tiquetes", estos son ideas, flujo de retroalimentación (como por ejemplo este tiquete), tareas o errores que se identifican o generan cuando el proyecto que se esta desarrollando avanza.

Para resolver un tiquete puede ser necesario un cambio para mejor al código del upstream de donde has generado tu repositorio origin por medio de la opción fork en GitHub, para después clonarlo y así trabajar en el directorio local. 

Después de trabajar en el directorio local has generado cambios en el código, para resolver este tiquete entonces solicitas al propietario (o a un encargado en el proyecto) del repositorio upstream una "Solicitud de Fusión" o "Pull Request", este revisara los cambios en el código, y sí estos estas alineados al objetivo del tiquete y a los objetivos del proyecto, para después fusionar la propuesta de mejora con el código del upstream.
